remote:
  url: 127.0.0.1:9999
feign:
  hystrix:
    enabled: true
spring:
  profiles:
    include: common
  application:
    name: PRODUCT-PROVIDER
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#ribbon:
#  ...配置ribbon的相关参数
#     参数相关的配置文件在core包的client的config下
