feign:
  hystrix:
    enabled: true
spring:
  profiles:
    include: common
  application:
    name: RAW-PROVIDER
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
